spring.application.name=spring-data-jpa-handson
spring.datasource.url=jdbc:mysql://localhost:3306/springdatajpa
spring.datasource.username=root
spring.datasource.password=Rsy0794

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
